services:
  ollama:
    volumes:
      - ~/ollama/ollama:/root/.ollama
    container_name: ollama-w
    pull_policy: always
    tty: true
    image: ollama/ollama:latest
    ports:
      - 11434:11434
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]
  asr-indic-server:
    image: slabstech/asr_indic_server_12_6
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface
    ports:
      - 7860:7860
    environment:
      - LANGUAGE=kn
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]
  tts-indic-server:
    image: slabstech/tts_indic_server_12_6
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface
    ports:
      - 7860:7860
    environment:
      - LANGUAGE=kn
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]
  indic-translate-server:
    image: slabstech/indic_translate_server_12_6
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface
    ports:
      - 7860:7860
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]