services:
  asr-indic-server:
    image: slabstech/asr_indic_server_12_6
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface
    ports:
      - 8860:7860
    environment:
      - LANGUAGE=kn
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]
  indic-translate-server:
    image: slabstech/indic_translate_server_12_6
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface
    ports:
      - 10860:7860
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]